### ISSUE TITLE
App Description

### ISSUE THREAD

**Issue by jbesraa** [CYPIAPT-LNDSE/sdm-app#25]
Hi @rosatown,

We are planning to write a little description about the application in the landing page.
here is what we came up with: 

"
This application intends to provide you with information
about the available treatments for your disorder; so you can make a calculated decision regarding the treatment that most suits you.
"

if you have any comments about it, let us know please (:

**Comment by rosatown** [comment]
Hi Esraa,


Thanks for sending this over. I will send you a slightly edited version of both of the excerpts you sent me shortly--I am currently at a conference. 


Best wishes,


Rosa 

Sent from my iPhone

On 1 Feb 2017, at 14:49, Esraa Jbara <notifications@github.com> wrote:




Hi @rosatown,
We are planning to write a little description about the application in the landing page.
here is what we came up with:
"
This application intends to provide you with information
about the available treatments for your disorder; so you can make a calculated decision regarding the treatment that most suits you.
"
if you have any comments about it, let us know please (:
—
You are receiving this because you were assigned.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.






{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CYPIAPT-LNDSE/sdm-app","title":"CYPIAPT-LNDSE/sdm-app","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/CYPIAPT-LNDSE/sdm-app"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"App Description (#25)"}],"action":{"name":"View Issue","url":"https://github.com/CYPIAPT-LNDSE/sdm-app/issues/25"}}}


  This email has been scanned for email related threats and delivered safely by Mimecast. For more information please visit http://www.mimecast.com

**Comment by rosatown** [comment]
Okay here's a slightly edited version of the second one: 


This application will provide you with evidence-based information about the treatment or support options for your difficulties. This will help you make an informed decision about your care.
